trees:
- tree: databroker.experimental.server_ext:MongoAdapter.from_mongomock
  path: /
  args:
    directory: ./data_files

specs:
  - spec: test
    validator: lightway.validators:validate_ExperimentalXASMetadata

reject_undeclared_specs: true
